job('First-Maven-Project-Via-DSL-2') {
    description("First Maven job generated by the DSL on ${new Date()}, the project is a small Maven project hosted on github")
    scm {
        git("https://github.com/demilbr1/DevOpsTraining.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'Jenkins_Upgradev3/maven-samples/single-module/pom.xml')
		maven {mavenInstallation('mvn')}
		
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}